# Generated by Django 2.1.3 on 2018-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PARTICIPANT', 'participant')], max_length=10),
        ),
    ]
