# Generated by Django 2.1.3 on 2019-01-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxonomyabundance',
            old_name='rank7_strain',
            new_name='rank7_species',
        ),
        migrations.AddField(
            model_name='taxonomyabundance',
            name='rank8_strain',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
