# Generated by Django 2.1.3 on 2019-01-15 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyAbundance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abundance', models.IntegerField()),
                ('rank1_kingdom', models.CharField(max_length=100)),
                ('rank2_phylum', models.CharField(max_length=100)),
                ('rank3_class', models.CharField(max_length=100)),
                ('rank4_order', models.CharField(max_length=100)),
                ('rank5_family', models.CharField(max_length=100)),
                ('rank6_genus', models.CharField(max_length=100)),
                ('rank7_strain', models.CharField(max_length=100)),
                ('sample_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_files', to='app.SampleFiles')),
            ],
        ),
    ]
