# Generated by Django 2.1.3 on 2018-11-30 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181130_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, max_length=40000),
        ),
        migrations.AddField(
            model_name='sample',
            name='name',
            field=models.CharField(default=2, max_length=240),
            preserve_default=False,
        ),
    ]
