# Generated by Django 2.1.3 on 2019-01-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190117_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='abundance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
