# Generated by Django 2.1.3 on 2019-01-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190117_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='abundance',
            field=models.DecimalField(decimal_places=10, max_digits=18),
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank2_phylum',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank3_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank4_order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank5_family',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank6_genus',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank7_species',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank8_strain',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
