# Generated by Django 2.1.3 on 2018-11-24 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181124_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_admins',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
