# Generated by Django 2.1.3 on 2018-11-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181130_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplefiles',
            name='description',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='description',
            field=models.TextField(blank=True, max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='samplefiles',
            name='file_name',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='samplefiles',
            name='type',
            field=models.CharField(max_length=40),
        ),
    ]
