# Generated by Django 2.1.3 on 2019-01-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190118_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaxonomyIdAbundance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abundance', models.DecimalField(decimal_places=10, max_digits=18)),
                ('rank1_kingdom', models.IntegerField()),
                ('rank2_phylum', models.IntegerField(blank=True, null=True)),
                ('rank3_class', models.IntegerField(blank=True, null=True)),
                ('rank4_order', models.IntegerField(blank=True, null=True)),
                ('rank5_family', models.IntegerField(blank=True, null=True)),
                ('rank6_genus', models.IntegerField(blank=True, null=True)),
                ('rank7_species', models.IntegerField(blank=True, null=True)),
                ('rank8_strain', models.IntegerField(blank=True, null=True)),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_taxonomy_id_abundances', to='app.Sample')),
            ],
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank1_kingdom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taxonomyabundance',
            name='rank2_phylum',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddIndex(
            model_name='taxnames',
            index=models.Index(fields=['name'], name='app_taxname_name_0a0c73_idx'),
        ),
    ]
